Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> python.el: native completion setup loaded
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/Python.py", line 3, in <module>
    import mathplotlib.pyplot as plt 
ModuleNotFoundError: No module named 'mathplotlib'
>>> Set the label for the y-axis.
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/Puz1Conform.py", line 19, in <module>
NameError: name 'F' is not defined
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/Puz1Conform.py", line 19, in <module>
NameError: name 'F' is not defined
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/Puz1Conform.py", line 19, in <module>
NameError: name 'F' is not defined
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/Puz1Conform.py", line 20, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/Puz1Conform.py", line 9, in Conform
TypeError: list indices must be integers or slices, not str
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/Puz1Conform.py", line 20, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/Puz1Conform.py", line 7, in Conform
    
TypeError: 'list' object cannot be interpreted as an integer
>>> From,  4  till,  5 you must turn
From,  7  till,  7 you must turn
From,  9  till,  10 you must turn
From,  12  till,  12 you must turn
>>> From,  4  till  5 , you must turn
From,  7  till  7 , you must turn
From,  9  till  10 , you must turn
From,  12  till  12 , you must turn
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 3, in <module>
NameError: name 'beyonce' is not defined
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 5, in <module>
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Á line 5, in <module>
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 5, in <module>
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 5, in <module>
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 5, in <module>
TypeError: 'int' object is not iterable
>>> beyonce
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'beyonce' is not defined
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 5, in <module>
    beyonce = set(6)
TypeError: 'int' object is not iterable
>>> beyonce
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'beyonce' is not defined
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 4, in <module>
    
ValueError: not enough values to unpack (expected 7, got 0)
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 4, in <module>
    
ValueError: too many values to unpack (expected 7)
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 6, in <module>
    taylor = set(7,8)
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 5, in <module>
    beyonce = set(6)
TypeError: descriptor 'add' requires a 'set' object but received a 'int'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 5, in <module>
    beyonce = set(6)
TypeError: descriptor 'add' requires a 'set' object but received a 'list'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 5
    beyonce = set.(6)
                  ^
SyntaxError: invalid syntax
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 5, in <module>
    beyonce = set(6)
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 4, in <module>
    
ValueError: too many values to unpack (expected 7)
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 4, in <module>
    
ValueError: too many values to unpack (expected 7)
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 7, in <module>
    brad = set(10)
TypeError: descriptor 'add' requires a 'set' object but received a 'int'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 7, in <module>
    brad = set(10)
TypeError: descriptor 'add' requires a 'set' object but received a 'int'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 7, in <module>
    brad = set(10)
TypeError: descriptor 'add' requires a 'set' object but received a 'int'
>>> s = set()
>>> s
set()
>>> s = set(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not iterable
>>> s = set.add(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor 'add' requires a 'set' object but received a 'int'
>>> s = add(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'add' is not defined
>>> s.add(1)
>>> s
{1}
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 8, in <module>
    katy = set(10, 11)
TypeError: unhashable type: 'list'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 8, in <module>
    katy = set(10, 11)
TypeError: add() takes exactly one argument (2 given)
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 8, in <module>
    katy = set(10, 11)
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 8, in <module>
    katy = set(10, 11)
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 8, in <module>
    taylor = taylor.union(7,8)
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 10, in <module>
    katy = katy.union(10, 11)
TypeError: 'int' object is not iterable
>>> taylor
{8, 7}
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 13, in <module>
    alicia = alicia.union(6,7)
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 17, in <module>
    S = set(beyonce,tom, taylor, drake, brad, katy, tom, drake, alicia)
TypeError: set expected at most 1 arguments, got 9
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 17, in <module>
    S = set(beyonce,tom, taylor, drake, brad, katy, tom, drake, alicia)
TypeError: unhashable type: 'set'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 17, in <module>
    S = S.union((beyonce,tom, taylor, drake, brad, katy, tom, drake, alicia))
TypeError: unhashable type: 'set'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 17, in <module>
    S = S.union((beyonce,tom, taylor, drake, brad, katy, tom, drake, alicia))
TypeError: unhashable type: 'set'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 17, in <module>
    S = S.union((beyonce,tom, taylor, drake, brad, katy, tom, drake, alicia))
TypeError: unhashable type: 'set'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 17, in <module>
    S = S.add((beyonce,tom, taylor, drake, brad, katy, tom, drake, alicia))
TypeError: unhashable type: 'set'
>>> s
{1}
>>> S
[None, {8, 9}, {8, 7}, {9, 10}, None, {10, 11}, {8, 9}, {9, 10}, {6, 7}]
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 7, in <module>
    beyonce = beyonce.add(6)
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 7, in <module>
    beyonce = beyonce.add(6)
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 7, in <module>
    beyonce = beyonce.union((6))
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 7, in <module>
    beyonce = beyonce.union((6))
TypeError: 'int' object is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 9, in <module>
    brad = brad.union((10))
TypeError: 'int' object is not iterable
>>> beyonce
>>> beyonce
>>> show(beyince
... 
...   C-c C-c
Process Python interrupção
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> python.el: native completion setup loaded
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 9, in <module>
    brad = brad.union((10))
TypeError: 'int' object is not iterable
>>> show(beyonce)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'show' is not defined
>>> beyonce
>>> taylor
{8, 7}
>>> 
>>> S
[{6}, {8, 9}, {8, 7}, {9, 10}, {10}, {10, 11}, {8, 9}, {9, 10}, {6, 7}]
>>> best(S)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 27, in best
    Union = set.union(Union,st) ## We have all possible hours, now
TypeError: descriptor 'union' requires a 'set' object but received a 'type'
>>> best(S)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 32, in best
    count[hr] +=  1 
KeyError: 6
>>> count = {}
>>> count
{}
>>> count[1] = 2
>>> count
{1: 2}
>>> count[2] = 3
>>> count
{1: 2, 2: 3}
>>> max(count)
2
>>> S
[{6}, {8, 9}, {8, 7}, {9, 10}, {10}, {10, 11}, {8, 9}, {9, 10}, {6, 7}]
>>> Union
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Union' is not defined
>>> best(S)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 30, in best
    if hr in (st in S):
TypeError: argument of type 'bool' is not iterable
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 30
    if hr in (for st in S):
                ^
SyntaxError: invalid syntax
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 30
    if hr in (for st in S):
                ^
SyntaxError: invalid syntax
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 30
    if hr in (for st in S):
                ^
SyntaxError: invalid syntax
>>> best(S)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Área de Trabalho/lin-portacle/portacle/projects/PuzzlesMIT/puz2Party.py", line 30, in best
    if hr in (for st in S):
TypeError: argument of type 'bool' is not iterable
>>> beyonce in S
True
>>> A = set.union(set(),beyonce)
>>> A
{6}
>>> A = set.union(A, katy)
>>> A
{10, 11, 6}
>>> Union
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Union' is not defined
>>> 